### ISSUE TITLE
Issue with dual wield dagger

### ISSUE THREAD

**Issue by RazzSG** [Malekitsu/MM6-MAW-Monster-Arts-and-Wonders#6]
When I equip daggers in both hands, I'm getting this exception

![image](https://user-images.githubusercontent.com/51904365/206908591-b20ff179-e36e-4d83-a836-18c2240640d1.png)

**Comment by RazzSG** [comment]
Update: It happens when I click on the Stats button

**Comment by Eksekk** [comment]
Fixed in 163593b15fa4b70e74229409b230654e0acc8ee2
