### ISSUE TITLE
Game crashes when a PC is hit by a theft attack

### ISSUE THREAD

**Issue by Tomsod** [Malekitsu/MM6-MAW-Monster-Arts-and-Wonders#7]
Apparently successful item theft causes crashes.  I'm told that theft attacks are currently disabled in vanilla as a workaround, but it's not the case for TCC, and there's a bunch of item thieves there, so it's somewhat annoying.

**Comment by Eksekk** [comment]
I think I fixed it in 188746ad83bca4f2ac81e22ace9c4306b559fa68 (someone else had the same problem and said the fix works), could you also verify?

**Comment by Tomsod** [comment]
Yes, this works, thanks.
